// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

Future<String> coreLoginWithPwd(
        {required String account, String? password, String? region}) =>
    RustLib.instance.api.crateApiAuthCoreLoginWithPwd(
        account: account, password: password, region: region);

Future<String> coreLoginOrRegisterByCode(
        {required String mobile, required String code, String? region}) =>
    RustLib.instance.api.crateApiAuthCoreLoginOrRegisterByCode(
        mobile: mobile, code: code, region: region);

Future<void> coreRegister(
        {required String account,
        String? password,
        String? nickname,
        String? avatar,
        String? region}) =>
    RustLib.instance.api.crateApiAuthCoreRegister(
        account: account,
        password: password,
        nickname: nickname,
        avatar: avatar,
        region: region);

Future<void> coreSendVerifyCode({required String mobile}) =>
    RustLib.instance.api.crateApiAuthCoreSendVerifyCode(mobile: mobile);

Future<void> coreLogout() => RustLib.instance.api.crateApiAuthCoreLogout();
