// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FLUTTER_STREAM`, `GLOBAL_DB`, `GLOBAL_WS_CLIENT`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `deref`, `initialize`, `initialize`, `initialize`

Future<void> coreInitSdk({required String dbPath}) =>
    RustLib.instance.api.crateApiImCoreInitSdk(dbPath: dbPath);

Future<void> coreStartWs(
        {required String url,
        required String token,
        required String clientId}) =>
    RustLib.instance.api
        .crateApiImCoreStartWs(url: url, token: token, clientId: clientId);

Stream<XEvent> coreSubscribeImEvents() =>
    RustLib.instance.api.crateApiImCoreSubscribeImEvents();

Future<String> coreSendTextMessage(
        {required BigInt roomId,
        required String content,
        required BigInt senderUid}) =>
    RustLib.instance.api.crateApiImCoreSendTextMessage(
        roomId: roomId, content: content, senderUid: senderUid);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<XEvent>>
abstract class XEvent implements RustOpaqueInterface {}
