// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

Future<String> coreUploadFile(
        {required List<int> fileBytes,
        required String filename,
        required String scene}) =>
    RustLib.instance.api.crateApiOssCoreUploadFile(
        fileBytes: fileBytes, filename: filename, scene: scene);
