// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'frb_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GLOBAL_API_CLIENT`, `GLOBAL_STORAGE`, `MobileStorageAdapter`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `get`, `initialize`, `initialize`, `remove`, `set`

void initApp() => RustLib.instance.api.crateApiInitApp();

Future<String> pingCore() => RustLib.instance.api.crateApiPingCore();

Future<String> coreLoginWithPwd({required String account, String? password, String? region}) =>
    RustLib.instance.api
        .crateApiCoreLoginWithPwd(account: account, password: password, region: region);

Future<String> coreLoginOrRegisterByCode(
        {required String mobile, required String code, String? region}) =>
    RustLib.instance.api
        .crateApiCoreLoginOrRegisterByCode(mobile: mobile, code: code, region: region);

Future<void> coreRegister(
        {required String account, String? password, String? nickname, String? avatar, String? region}) =>
    RustLib.instance.api.crateApiCoreRegister(
        account: account, password: password, nickname: nickname, avatar: avatar, region: region);

Future<void> coreSendVerifyCode({required String mobile}) =>
    RustLib.instance.api.crateApiCoreSendVerifyCode(mobile: mobile);
