// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'api.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  RustLib._();
  @internal
  static final RustLib instance = RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 374593822;

  static const ExternalLibraryLoaderConfig kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_wechat_flutter',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiCoreLoginOrRegisterByCode(
      {required String mobile, required String code, String? region});

  Future<String> crateApiCoreLoginWithPwd(
      {required String account, String? password, String? region});

  Future<void> crateApiCoreLogout();

  Future<void> crateApiCoreRegister(
      {required String account,
      String? password,
      String? nickname,
      String? avatar,
      String? region});

  Future<void> crateApiCoreSendVerifyCode({required String mobile});

  Future<String> crateApiCoreUploadFile(
      {required List<int> fileBytes,
      required String filename,
      required String scene});

  void crateApiInitApp();

  Future<String> crateApiPingCore();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiCoreLoginOrRegisterByCode(
      {required String mobile, required String code, String? region}) {
    return handler.executeNormal(NormalTask(
      callFfi: (NativePortType port_) {
        final SseSerializer serializer =
            SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(mobile, serializer);
        sse_encode_String(code, serializer);
        sse_encode_opt_String(region, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCoreLoginOrRegisterByCodeConstMeta,
      argValues: <dynamic>[mobile, code, region],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreLoginOrRegisterByCodeConstMeta =>
      const TaskConstMeta(
        debugName: 'core_login_or_register_by_code',
        argNames: <String>['mobile', 'code', 'region'],
      );

  @override
  Future<String> crateApiCoreLoginWithPwd(
      {required String account, String? password, String? region}) {
    return handler.executeNormal(NormalTask(
      callFfi: (NativePortType port_) {
        final SseSerializer serializer =
            SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(account, serializer);
        sse_encode_opt_String(password, serializer);
        sse_encode_opt_String(region, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCoreLoginWithPwdConstMeta,
      argValues: <dynamic>[account, password, region],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreLoginWithPwdConstMeta => const TaskConstMeta(
        debugName: 'core_login_with_pwd',
        argNames: <String>['account', 'password', 'region'],
      );

  @override
  Future<void> crateApiCoreLogout() {
    return handler.executeNormal(NormalTask(
      callFfi: (NativePortType port_) {
        final SseSerializer serializer =
            SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCoreLogoutConstMeta,
      argValues: <dynamic>[],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreLogoutConstMeta => const TaskConstMeta(
        debugName: 'core_logout',
        argNames: <String>[],
      );

  @override
  Future<void> crateApiCoreRegister(
      {required String account,
      String? password,
      String? nickname,
      String? avatar,
      String? region}) {
    return handler.executeNormal(NormalTask(
      callFfi: (NativePortType port_) {
        final SseSerializer serializer =
            SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(account, serializer);
        sse_encode_opt_String(password, serializer);
        sse_encode_opt_String(nickname, serializer);
        sse_encode_opt_String(avatar, serializer);
        sse_encode_opt_String(region, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCoreRegisterConstMeta,
      argValues: <dynamic>[account, password, nickname, avatar, region],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreRegisterConstMeta => const TaskConstMeta(
        debugName: 'core_register',
        argNames: <String>[
          'account',
          'password',
          'nickname',
          'avatar',
          'region'
        ],
      );

  @override
  Future<void> crateApiCoreSendVerifyCode({required String mobile}) {
    return handler.executeNormal(NormalTask(
      callFfi: (NativePortType port_) {
        final SseSerializer serializer =
            SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(mobile, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCoreSendVerifyCodeConstMeta,
      argValues: <dynamic>[mobile],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreSendVerifyCodeConstMeta => const TaskConstMeta(
        debugName: 'core_send_verify_code',
        argNames: <String>['mobile'],
      );

  @override
  Future<String> crateApiCoreUploadFile(
      {required List<int> fileBytes,
      required String filename,
      required String scene}) {
    return handler.executeNormal(NormalTask(
      callFfi: (NativePortType port_) {
        final SseSerializer serializer =
            SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(fileBytes, serializer);
        sse_encode_String(filename, serializer);
        sse_encode_String(scene, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCoreUploadFileConstMeta,
      argValues: <dynamic>[fileBytes, filename, scene],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreUploadFileConstMeta => const TaskConstMeta(
        debugName: 'core_upload_file',
        argNames: <String>['fileBytes', 'filename', 'scene'],
      );

  @override
  void crateApiInitApp() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final SseSerializer serializer =
            SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInitAppConstMeta,
      argValues: <dynamic>[],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitAppConstMeta => const TaskConstMeta(
        debugName: 'init_app',
        argNames: <String>[],
      );

  @override
  Future<String> crateApiPingCore() {
    return handler.executeNormal(NormalTask(
      callFfi: (NativePortType port_) {
        final SseSerializer serializer =
            SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiPingCoreConstMeta,
      argValues: <dynamic>[],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPingCoreConstMeta => const TaskConstMeta(
        debugName: 'ping_core',
        argNames: <String>[],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final Uint8List inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final int len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final int len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return sse_decode_String(deserializer);
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
