// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api/auth.dart';
import 'api/common.dart';
import 'api/im.dart';
import 'api/oss.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1561997062;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_wechat_flutter',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<MobileStorageAdapter> crateApiMobileStorageAdapterNew();

  Future<void> crateApiImCoreAddFriend(
      {required PlatformInt64 targetUid, String? message});

  Future<void> crateApiImCoreApproveFriendApply(
      {required PlatformInt64 applyId});

  Future<String> crateApiImCoreCreateGroup(
      {required String name,
      required Int64List memberUids,
      String? introduction});

  Future<void> crateApiImCoreDeleteContact({required PlatformInt64 roomId});

  Future<void> crateApiImCoreDeleteFriend({required PlatformInt64 targetUid});

  Future<void> crateApiImCoreDismissGroup({required PlatformInt64 groupId});

  Future<String> crateApiImCoreGetContacts();

  Future<String> crateApiImCoreGetGroupInfo({required PlatformInt64 groupId});

  Future<String> crateApiImCoreGetHistoryMessages(
      {required PlatformInt64 roomId, required PlatformInt64 limit});

  Future<String> crateApiImCoreGetUserInfo({required PlatformInt64 userId});

  Future<String> crateApiImCoreGetUsersInfo({required Int64List userIds});

  Future<void> crateApiImCoreInitSdk({required String dbPath});

  Future<void> crateApiImCoreInviteMembers(
      {required PlatformInt64 groupId, required Int64List memberUids});

  Future<void> crateApiImCoreKickMember(
      {required PlatformInt64 groupId, required PlatformInt64 userId});

  Future<String> crateApiImCoreListFriendApplies();

  Future<String> crateApiImCoreListFriends();

  Future<String> crateApiImCoreListGroupMembers(
      {required PlatformInt64 groupId});

  Future<String> crateApiAuthCoreLoginOrRegisterByCode(
      {required String mobile, required String code, String? region});

  Future<String> crateApiAuthCoreLoginWithPwd(
      {required String account, String? password, String? region});

  Future<void> crateApiAuthCoreLogout();

  Future<void> crateApiImCoreMarkRead({required PlatformInt64 roomId});

  Future<String> crateApiImCorePullRemoteMessages(
      {required PlatformInt64 roomId,
      PlatformInt64? cursor,
      required PlatformInt64 limit});

  Future<void> crateApiImCoreQuitGroup({required PlatformInt64 groupId});

  Future<void> crateApiAuthCoreRegister(
      {required String account,
      String? password,
      String? nickname,
      String? avatar,
      String? region});

  Future<void> crateApiImCoreRejectFriendApply(
      {required PlatformInt64 applyId});

  Future<String> crateApiImCoreSearchUser({required String keyword});

  Future<String> crateApiImCoreSendTextMessage(
      {required PlatformInt64 roomId,
      required String content,
      required PlatformInt64 fromUid});

  Future<void> crateApiAuthCoreSendVerifyCode({required String mobile});

  Future<void> crateApiImCoreStartWs(
      {required String url,
      required String clientId,
      required bool syncChatHistory});

  Stream<String> crateApiImCoreSubscribeImEvents();

  Future<String> crateApiImCoreUpdateGroupInfo(
      {required PlatformInt64 groupId,
      String? name,
      String? faceUrl,
      String? introduction,
      String? notification});

  Future<void> crateApiImCoreUpdateTokens(
      {required String accessToken,
      required String refreshToken,
      PlatformInt64? accessExpiresAt,
      PlatformInt64? refreshExpiresAt});

  Future<String> crateApiImCoreUpdateUserInfo(
      {required PlatformInt64 userId,
      String? nickName,
      String? faceUrl,
      String? selfSignature,
      int? gender});

  Future<String> crateApiOssCoreUploadFile(
      {required List<int> fileBytes,
      required String filename,
      required String scene});

  void crateApiCommonInitApp();

  Future<String> crateApiCommonPingCore();

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_MobileStorageAdapter;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_MobileStorageAdapter;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_MobileStorageAdapterPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<MobileStorageAdapter> crateApiMobileStorageAdapterNew() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileStorageAdapter,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMobileStorageAdapterNewConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMobileStorageAdapterNewConstMeta =>
      const TaskConstMeta(
        debugName: "MobileStorageAdapter_new",
        argNames: [],
      );

  @override
  Future<void> crateApiImCoreAddFriend(
      {required PlatformInt64 targetUid, String? message}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(targetUid, serializer);
        sse_encode_opt_String(message, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreAddFriendConstMeta,
      argValues: [targetUid, message],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreAddFriendConstMeta => const TaskConstMeta(
        debugName: "core_add_friend",
        argNames: ["targetUid", "message"],
      );

  @override
  Future<void> crateApiImCoreApproveFriendApply(
      {required PlatformInt64 applyId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(applyId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreApproveFriendApplyConstMeta,
      argValues: [applyId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreApproveFriendApplyConstMeta =>
      const TaskConstMeta(
        debugName: "core_approve_friend_apply",
        argNames: ["applyId"],
      );

  @override
  Future<String> crateApiImCoreCreateGroup(
      {required String name,
      required Int64List memberUids,
      String? introduction}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        sse_encode_list_prim_i_64_strict(memberUids, serializer);
        sse_encode_opt_String(introduction, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreCreateGroupConstMeta,
      argValues: [name, memberUids, introduction],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreCreateGroupConstMeta => const TaskConstMeta(
        debugName: "core_create_group",
        argNames: ["name", "memberUids", "introduction"],
      );

  @override
  Future<void> crateApiImCoreDeleteContact({required PlatformInt64 roomId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(roomId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreDeleteContactConstMeta,
      argValues: [roomId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreDeleteContactConstMeta =>
      const TaskConstMeta(
        debugName: "core_delete_contact",
        argNames: ["roomId"],
      );

  @override
  Future<void> crateApiImCoreDeleteFriend({required PlatformInt64 targetUid}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(targetUid, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreDeleteFriendConstMeta,
      argValues: [targetUid],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreDeleteFriendConstMeta => const TaskConstMeta(
        debugName: "core_delete_friend",
        argNames: ["targetUid"],
      );

  @override
  Future<void> crateApiImCoreDismissGroup({required PlatformInt64 groupId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(groupId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreDismissGroupConstMeta,
      argValues: [groupId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreDismissGroupConstMeta => const TaskConstMeta(
        debugName: "core_dismiss_group",
        argNames: ["groupId"],
      );

  @override
  Future<String> crateApiImCoreGetContacts() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreGetContactsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreGetContactsConstMeta => const TaskConstMeta(
        debugName: "core_get_contacts",
        argNames: [],
      );

  @override
  Future<String> crateApiImCoreGetGroupInfo({required PlatformInt64 groupId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(groupId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreGetGroupInfoConstMeta,
      argValues: [groupId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreGetGroupInfoConstMeta => const TaskConstMeta(
        debugName: "core_get_group_info",
        argNames: ["groupId"],
      );

  @override
  Future<String> crateApiImCoreGetHistoryMessages(
      {required PlatformInt64 roomId, required PlatformInt64 limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(roomId, serializer);
        sse_encode_i_64(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreGetHistoryMessagesConstMeta,
      argValues: [roomId, limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreGetHistoryMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "core_get_history_messages",
        argNames: ["roomId", "limit"],
      );

  @override
  Future<String> crateApiImCoreGetUserInfo({required PlatformInt64 userId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(userId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreGetUserInfoConstMeta,
      argValues: [userId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreGetUserInfoConstMeta => const TaskConstMeta(
        debugName: "core_get_user_info",
        argNames: ["userId"],
      );

  @override
  Future<String> crateApiImCoreGetUsersInfo({required Int64List userIds}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_i_64_strict(userIds, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreGetUsersInfoConstMeta,
      argValues: [userIds],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreGetUsersInfoConstMeta => const TaskConstMeta(
        debugName: "core_get_users_info",
        argNames: ["userIds"],
      );

  @override
  Future<void> crateApiImCoreInitSdk({required String dbPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreInitSdkConstMeta,
      argValues: [dbPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreInitSdkConstMeta => const TaskConstMeta(
        debugName: "core_init_sdk",
        argNames: ["dbPath"],
      );

  @override
  Future<void> crateApiImCoreInviteMembers(
      {required PlatformInt64 groupId, required Int64List memberUids}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(groupId, serializer);
        sse_encode_list_prim_i_64_strict(memberUids, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreInviteMembersConstMeta,
      argValues: [groupId, memberUids],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreInviteMembersConstMeta =>
      const TaskConstMeta(
        debugName: "core_invite_members",
        argNames: ["groupId", "memberUids"],
      );

  @override
  Future<void> crateApiImCoreKickMember(
      {required PlatformInt64 groupId, required PlatformInt64 userId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(groupId, serializer);
        sse_encode_i_64(userId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreKickMemberConstMeta,
      argValues: [groupId, userId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreKickMemberConstMeta => const TaskConstMeta(
        debugName: "core_kick_member",
        argNames: ["groupId", "userId"],
      );

  @override
  Future<String> crateApiImCoreListFriendApplies() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreListFriendAppliesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreListFriendAppliesConstMeta =>
      const TaskConstMeta(
        debugName: "core_list_friend_applies",
        argNames: [],
      );

  @override
  Future<String> crateApiImCoreListFriends() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreListFriendsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreListFriendsConstMeta => const TaskConstMeta(
        debugName: "core_list_friends",
        argNames: [],
      );

  @override
  Future<String> crateApiImCoreListGroupMembers(
      {required PlatformInt64 groupId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(groupId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreListGroupMembersConstMeta,
      argValues: [groupId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreListGroupMembersConstMeta =>
      const TaskConstMeta(
        debugName: "core_list_group_members",
        argNames: ["groupId"],
      );

  @override
  Future<String> crateApiAuthCoreLoginOrRegisterByCode(
      {required String mobile, required String code, String? region}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(mobile, serializer);
        sse_encode_String(code, serializer);
        sse_encode_opt_String(region, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAuthCoreLoginOrRegisterByCodeConstMeta,
      argValues: [mobile, code, region],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAuthCoreLoginOrRegisterByCodeConstMeta =>
      const TaskConstMeta(
        debugName: "core_login_or_register_by_code",
        argNames: ["mobile", "code", "region"],
      );

  @override
  Future<String> crateApiAuthCoreLoginWithPwd(
      {required String account, String? password, String? region}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(account, serializer);
        sse_encode_opt_String(password, serializer);
        sse_encode_opt_String(region, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAuthCoreLoginWithPwdConstMeta,
      argValues: [account, password, region],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAuthCoreLoginWithPwdConstMeta =>
      const TaskConstMeta(
        debugName: "core_login_with_pwd",
        argNames: ["account", "password", "region"],
      );

  @override
  Future<void> crateApiAuthCoreLogout() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAuthCoreLogoutConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAuthCoreLogoutConstMeta => const TaskConstMeta(
        debugName: "core_logout",
        argNames: [],
      );

  @override
  Future<void> crateApiImCoreMarkRead({required PlatformInt64 roomId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(roomId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreMarkReadConstMeta,
      argValues: [roomId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreMarkReadConstMeta => const TaskConstMeta(
        debugName: "core_mark_read",
        argNames: ["roomId"],
      );

  @override
  Future<String> crateApiImCorePullRemoteMessages(
      {required PlatformInt64 roomId,
      PlatformInt64? cursor,
      required PlatformInt64 limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(roomId, serializer);
        sse_encode_opt_box_autoadd_i_64(cursor, serializer);
        sse_encode_i_64(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCorePullRemoteMessagesConstMeta,
      argValues: [roomId, cursor, limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCorePullRemoteMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "core_pull_remote_messages",
        argNames: ["roomId", "cursor", "limit"],
      );

  @override
  Future<void> crateApiImCoreQuitGroup({required PlatformInt64 groupId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(groupId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreQuitGroupConstMeta,
      argValues: [groupId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreQuitGroupConstMeta => const TaskConstMeta(
        debugName: "core_quit_group",
        argNames: ["groupId"],
      );

  @override
  Future<void> crateApiAuthCoreRegister(
      {required String account,
      String? password,
      String? nickname,
      String? avatar,
      String? region}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(account, serializer);
        sse_encode_opt_String(password, serializer);
        sse_encode_opt_String(nickname, serializer);
        sse_encode_opt_String(avatar, serializer);
        sse_encode_opt_String(region, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAuthCoreRegisterConstMeta,
      argValues: [account, password, nickname, avatar, region],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAuthCoreRegisterConstMeta => const TaskConstMeta(
        debugName: "core_register",
        argNames: ["account", "password", "nickname", "avatar", "region"],
      );

  @override
  Future<void> crateApiImCoreRejectFriendApply(
      {required PlatformInt64 applyId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(applyId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreRejectFriendApplyConstMeta,
      argValues: [applyId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreRejectFriendApplyConstMeta =>
      const TaskConstMeta(
        debugName: "core_reject_friend_apply",
        argNames: ["applyId"],
      );

  @override
  Future<String> crateApiImCoreSearchUser({required String keyword}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(keyword, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 27, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreSearchUserConstMeta,
      argValues: [keyword],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreSearchUserConstMeta => const TaskConstMeta(
        debugName: "core_search_user",
        argNames: ["keyword"],
      );

  @override
  Future<String> crateApiImCoreSendTextMessage(
      {required PlatformInt64 roomId,
      required String content,
      required PlatformInt64 fromUid}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(roomId, serializer);
        sse_encode_String(content, serializer);
        sse_encode_i_64(fromUid, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 28, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreSendTextMessageConstMeta,
      argValues: [roomId, content, fromUid],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreSendTextMessageConstMeta =>
      const TaskConstMeta(
        debugName: "core_send_text_message",
        argNames: ["roomId", "content", "fromUid"],
      );

  @override
  Future<void> crateApiAuthCoreSendVerifyCode({required String mobile}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(mobile, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 29, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAuthCoreSendVerifyCodeConstMeta,
      argValues: [mobile],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAuthCoreSendVerifyCodeConstMeta =>
      const TaskConstMeta(
        debugName: "core_send_verify_code",
        argNames: ["mobile"],
      );

  @override
  Future<void> crateApiImCoreStartWs(
      {required String url,
      required String clientId,
      required bool syncChatHistory}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        sse_encode_String(clientId, serializer);
        sse_encode_bool(syncChatHistory, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 30, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreStartWsConstMeta,
      argValues: [url, clientId, syncChatHistory],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreStartWsConstMeta => const TaskConstMeta(
        debugName: "core_start_ws",
        argNames: ["url", "clientId", "syncChatHistory"],
      );

  @override
  Stream<String> crateApiImCoreSubscribeImEvents() {
    final sink = RustStreamSink<String>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_StreamSink_String_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 31, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiImCoreSubscribeImEventsConstMeta,
      argValues: [sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiImCoreSubscribeImEventsConstMeta =>
      const TaskConstMeta(
        debugName: "core_subscribe_im_events",
        argNames: ["sink"],
      );

  @override
  Future<String> crateApiImCoreUpdateGroupInfo(
      {required PlatformInt64 groupId,
      String? name,
      String? faceUrl,
      String? introduction,
      String? notification}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(groupId, serializer);
        sse_encode_opt_String(name, serializer);
        sse_encode_opt_String(faceUrl, serializer);
        sse_encode_opt_String(introduction, serializer);
        sse_encode_opt_String(notification, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 32, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreUpdateGroupInfoConstMeta,
      argValues: [groupId, name, faceUrl, introduction, notification],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreUpdateGroupInfoConstMeta =>
      const TaskConstMeta(
        debugName: "core_update_group_info",
        argNames: [
          "groupId",
          "name",
          "faceUrl",
          "introduction",
          "notification"
        ],
      );

  @override
  Future<void> crateApiImCoreUpdateTokens(
      {required String accessToken,
      required String refreshToken,
      PlatformInt64? accessExpiresAt,
      PlatformInt64? refreshExpiresAt}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(accessToken, serializer);
        sse_encode_String(refreshToken, serializer);
        sse_encode_opt_box_autoadd_i_64(accessExpiresAt, serializer);
        sse_encode_opt_box_autoadd_i_64(refreshExpiresAt, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 33, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiImCoreUpdateTokensConstMeta,
      argValues: [accessToken, refreshToken, accessExpiresAt, refreshExpiresAt],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreUpdateTokensConstMeta => const TaskConstMeta(
        debugName: "core_update_tokens",
        argNames: [
          "accessToken",
          "refreshToken",
          "accessExpiresAt",
          "refreshExpiresAt"
        ],
      );

  @override
  Future<String> crateApiImCoreUpdateUserInfo(
      {required PlatformInt64 userId,
      String? nickName,
      String? faceUrl,
      String? selfSignature,
      int? gender}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(userId, serializer);
        sse_encode_opt_String(nickName, serializer);
        sse_encode_opt_String(faceUrl, serializer);
        sse_encode_opt_String(selfSignature, serializer);
        sse_encode_opt_box_autoadd_i_32(gender, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 34, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImCoreUpdateUserInfoConstMeta,
      argValues: [userId, nickName, faceUrl, selfSignature, gender],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImCoreUpdateUserInfoConstMeta =>
      const TaskConstMeta(
        debugName: "core_update_user_info",
        argNames: ["userId", "nickName", "faceUrl", "selfSignature", "gender"],
      );

  @override
  Future<String> crateApiOssCoreUploadFile(
      {required List<int> fileBytes,
      required String filename,
      required String scene}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(fileBytes, serializer);
        sse_encode_String(filename, serializer);
        sse_encode_String(scene, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 35, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiOssCoreUploadFileConstMeta,
      argValues: [fileBytes, filename, scene],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOssCoreUploadFileConstMeta => const TaskConstMeta(
        debugName: "core_upload_file",
        argNames: ["fileBytes", "filename", "scene"],
      );

  @override
  void crateApiCommonInitApp() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 36)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCommonInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCommonInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<String> crateApiCommonPingCore() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 37, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCommonPingCoreConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCommonPingCoreConstMeta => const TaskConstMeta(
        debugName: "ping_core",
        argNames: [],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_MobileStorageAdapter => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileStorageAdapter;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_MobileStorageAdapter => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileStorageAdapter;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  MobileStorageAdapter
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileStorageAdapter(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MobileStorageAdapterImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MobileStorageAdapter
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileStorageAdapter(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MobileStorageAdapterImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeInt64List(raw);
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  MobileStorageAdapter
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileStorageAdapter(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MobileStorageAdapterImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  MobileStorageAdapter
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileStorageAdapter(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MobileStorageAdapterImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt64List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileStorageAdapter(
          MobileStorageAdapter self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as MobileStorageAdapterImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileStorageAdapter(
          MobileStorageAdapter self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as MobileStorageAdapterImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
      RustStreamSink<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_i_64_strict(
      Int64List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class MobileStorageAdapterImpl extends RustOpaque
    implements MobileStorageAdapter {
  // Not to be used by end users
  MobileStorageAdapterImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  MobileStorageAdapterImpl.frbInternalSseDecode(
      BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance.api.rust_arc_increment_strong_count_MobileStorageAdapter,
    rustArcDecrementStrongCount: RustLib
        .instance.api.rust_arc_decrement_strong_count_MobileStorageAdapter,
    rustArcDecrementStrongCountPtr: RustLib
        .instance.api.rust_arc_decrement_strong_count_MobileStorageAdapterPtr,
  );
}
